# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'HappyMind.xcworkspace'
platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'HappyMind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  # Pods for HappyMind
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'SDWebImage', '~> 5.0'
  pod 'SkeletonView'
  pod 'lottie-ios'
  pod 'Firebase/Messaging'
  pod 'MSAL'
  
  target 'HappyMindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HappyMindUITests' do
    # Pods for testing
  end
  
  target 'HappyMindCore' do
    inherit! :search_paths
    
    project 'HappyMindCore/HappyMindCore'
  end

  target 'HappyMindData' do
    inherit! :search_paths
    
    project 'HappyMindData/HappyMindData'
  end

end
